import streamlit as st

st.markdown("<h2 style='text-align: center; color: white; font-size: 40pt;'>Use TV broadcasts and highlight reels from games of the German DEL2 ice hockey league as input</h2>", True)
st.write("")
st.write("")
st.write("")
st.write("")
st.write("")
st.markdown("<h2 style='text-align: center; color: white; font-size: 40pt;'>Use footage from main camera only", True)
st.write("")
st.write("")
st.write("")
st.write("")
st.write("")
st.markdown("<h2 style='text-align: center; color: white; font-size: 40pt;'>Detect players, goalkeepers, referees and the physical goals while recognizing the different teams", True)
st.write("")
st.write("")
st.write("")
st.write("")
st.write("")
st.markdown("<h2 style='text-align: center; color: white; font-size: 40pt;'>Use those 6 classes to train pretrained YOLO v8 models", True)
